# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

stages:
- stage: Build
  jobs:
    - job: Build
      pool:
        #vmImage: 'VS2017-Win2016'
        name: Hosted VS2017
        demands:
        - msbuild
        - visualstudio
        - vtest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

#steps:
#- task: NuGetToolInstaller@1

#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# -- Begin: 
# - stage: Deploy
#   jobs:
#   - job: Deploy
#     pool:
#       name: Hosted VS2017
#     steps:
# -- End: 

- task: PublishSymbols@1
  displayName : 'Publish symbols path :'
  inputs:
    SearchPattern: '**\bin\**\.*.pdb'
    continueOnError: true

- task: CopyFiles@1
  displayName : 'Copy files to: $(build.artifactstagingdirectory)'
  inputs :
    SourceFolder : '$(build.sourcesdirectory)'
    contents : |
      **\bin\$(BuildConfiguration)\**
      src\*.testsettings
    TargetFolder: '$(build.artifactstagingdirectory)'

# --- this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishBuildArtifacts@1
  displayName : 'Publish artifacts: drop'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'GithubEmojis'
  condition : succeededOrFailed()

